{
 "title": "Pong Game Simple Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Requests respone time",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pong_game_http_request_duration_seconds_sum{method!=\"OPTIONS\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pong_game_process_resident_memory_bytes",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "req total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "pong_game_http_requests_total", "legendFormat": "{{route}}" }
   ]
  },
  {
   "title": "CPU Usage (Total Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pong_game_process_cpu_seconds_total",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "online users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "pong_game_active_connections", "legendFormat": "__auto" }
   ]
  }
 ]
}